Server/rails/ezmoto/config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :provinces
  resources :countries
  resources :drivers
  resources :custumers
  resources :users

  match 'mobile/login' => 'login_mobile#login', via: 'post'
  match 'mobile/logout' => 'login_mobile#logout', via: 'post'
  match 'mobile/users' => 'users#create_mobile', via: 'post'

end

Server/rails/ezmoto/app/models/province.rb
class Province < ActiveRecord::Base
   belongs_to :country
   has_many :cities

end

Server/rails/ezmoto/app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  before_action :set_province, only: [:show, :edit, :update, :destroy]

  # GET /provinces
  # GET /provinces.json
  def index
    @provinces = Province.all.order('name')
  end

  # GET /provinces/1
  # GET /provinces/1.json
  def show
  end

  # GET /provinces/new
  def new
    prepare_form
    @province = Province.new
  end

  # GET /provinces/1/edit
  def edit
    prepare_form
  end

  # POST /provinces
  # POST /provinces.json
  def create
    @province = Province.new(province_params)

    respond_to do |format|
      if @province.save
        format.html { redirect_to @province, notice: 'Province was successfully created.' }
        format.json { render :show, status: :created, location: @province }
      else
        prepare_form
        format.html { render :new }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provinces/1
  # PATCH/PUT /provinces/1.json
  def update
    respond_to do |format|
      if @province.update(province_params)
        format.html { redirect_to @province, notice: 'Province was successfully updated.' }
        format.json { render :show, status: :ok, location: @province }
      else
        prepare_form
        format.html { render :edit }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1
  # DELETE /provinces/1.json
  def destroy
    @province.destroy
    respond_to do |format|
      format.html { redirect_to provinces_url, notice: 'Province was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_province
      @province = Province.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def province_params
      params.require(:province).permit(:name, :initials, :country_id)
    end

    def prepare_form
      @countries = Country.order :name
    end

end

Server/rails/ezmoto/app/helpers/provinces_helper.rb
module ProvincesHelper
end

Server/rails/ezmoto/app/views/provinces/_form.html.erb
<%= form_for(@province) do |f| %>
  <% if @province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
      <% @province.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :initials %><br>
    <%= f.text_field :initials %>
  </div>
  <div class="field">
    <%= f.label :country_id %><br>
    <%= f.collection_select(:country_id, @countries, :id, :name, :prompt => true)  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Server/rails/ezmoto/app/views/provinces/edit.html.erb
<h1>Editing Province</h1>

<%= render 'form' %>

<%= link_to 'Show', @province %> |
<%= link_to 'Back', provinces_path %>

Server/rails/ezmoto/app/views/provinces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Provinces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Initials</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provinces.each do |province| %>
      <tr>
        <td><%= province.name %></td>
        <td><%= province.initials %></td>
        <td><%= province.country.name %></td>
        <td><%= link_to 'Show', province %></td>
        <td><%= link_to 'Edit', edit_province_path(province) %></td>
        <td><%= link_to 'Destroy', province, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Province', new_province_path %>

Server/rails/ezmoto/app/views/provinces/new.html.erb
<h1>New Province</h1>

<%= render 'form' %>

<%= link_to 'Back', provinces_path %>

Server/rails/ezmoto/app/views/provinces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @province.name %>
</p>

<p>
  <strong>Initials:</strong>
  <%= @province.initials %>
</p>

<p>
  <strong>Country:</strong>
  <%= @province.country.name %>
</p>

<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>